releases:
- name: fzf
  repo: junegunn/fzf
  version: ''
  file_list:
  - linux,amd64:amd64
  - linux,arm64:arm
- name: dust
  repo: bootandy/dust
  version: ''
  file_list:
  - x86_64-unknown-linux-gnu:amd64
  - arm-unknown-linux-gnu:arm
- name: eza
  repo: eza-community/eza
  version: ''
  file_list:
  - eza_arm-unknown-linux-gnueabihf:arm
  - eza_x86_64-unknown-linux-gnu:amd64
- name: caddy
  repo: caddyserver/caddy
  version: ''
  file_list:
  - linux_amd64,tar.gz:amd64
  - linux_arm64,tar.gz:arm
